FALL:
  enable: true
  extra: 10
  multiply: 2
  percentage: 0.5
#avalible
#BLOCK_EXPLOSION
#CONTACT
#CRAMMING
#CUSTOM
#DRAGON_BREATH
#DROWNING
#DRYOUT
#ENTITY_ATTACK
#ENTITY_EXPLOSION
#ENTITY_SWEEP_ATTACK
#FALL
#FALLING_BLOCK
#FIRE
#FIRE_TICK
#FLY_INTO_WALL
#HOT_FLOOR
#LAVA
#LIGHTNING
#MAGIC
#MELTING
#POISON
#PROJECTILE
#STARVATION
#SUFFOCATION
#SUICIDE
#THORNS
#VOID
#WITHER